### ISSUE TITLE
Blog post about the photo booth / booth at Drupalcon

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#18]
1. pics of the booth (here's a good one from geerlingguy https://www.flickr.com/photos/lifeisaprayer/34303458145/in/datetaken-friend/ but others are welcome!) 
2. some of our talking points maybe
3. what we felt like we accomplished
4. other fun things?
5. plz to write blog 4 website.

In order to do this, please assign the issue to yourself or comment that you're doing it, and then you can either open a pull request of an md file for a post, or post a google doc as a link.

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
