### ISSUE TITLE
Blog post about getting involved in DD&I

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#19]
It would be great to have a post by someone who got involved after the beginning talking about why they're involved and what it means to them.  

Maybe something warm and fuzzy, but also testimonal-ish?

In order to do this, please assign the issue to yourself or comment that you're doing it, and then you can either open a pull request of an md file for a post, or post a google doc as a link.

**Comment by sparklingrobots** [comment]
I'm already planning to write this and would be happy for it to live on the DD&I blog. (also maybe cross-post to my own blog if that is ok? Can be after it has been up on DD&I for a while with a link back to the original post.)  Also it will be the warmest and the fuzziest. 

I only have about 30 minutes right now but will aim to get at least a quick outline together and something more finished by early next week (May 2 or 3).

**Comment by sparklingrobots** [comment]
Also, not assigning to myself in case others want to write their own version. It's such a personal angle that I think we could have a pretty interesting set of posts.

**Comment by sugaroverflow** [comment]
I like the idea of having multiple of these posts and posting them over time. I would like to write one too, but maybe not just yet.

**Comment by jonpugh** [comment]
I was thinking of making it the topic of my next blog post on thinkdrop.net, which would go out over drupal planet. I'd be happy to cross post once it's up.

Had anyone thought of creating a blog with an RSS feed so you could submit tohttps://www.drupal.org/planet ?

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
