### ISSUE TITLE
Get RSS feed & other requirements met so we can join drupal planet.

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#20]
Here are the requirements:
https://www.drupal.org/drupalorg/docs/content/planet-drupal

The actionable (tldr) ones are:

1. You must have an RSS feed that contains only content appropriate for Drupal Planet. If your site uses Drupal, you can create a "Drupal Planet" taxonomy term and use it to tag any content you want to appear on the Planet. Drupal automatically creates an RSS feed for each taxonomy term, and you can submit that term’s feed URL in your Drupal Planet application. Alternatively, you can use the Drupal Planet feature module, which uses Flag and Views modules to create the feed. If you are not using Drupal, you will need to make sure your site can create a feed just for your Planet content.
Your feed must have at least two posts already so we can evaluate the content and make sure it is appropriate for the Planet.

1. Your feed must pass source code validation, since Drupal's aggregator module is very strict about parsing feed source code.

1. It is recommended that you trim, or use a summary for your feed content between 600 and 1000 characters. Due to the number of posts on the Planet, this will make it more pleasant for readers to find what is interesting for them without having to scroll page after page.

We probably won't be enabling comments on the blog posts (unless consensus dictates otherwise).

**Comment by cleverington** [comment]
From @justAChris 

> One comment I didn’t put on that request: I think drupal planet requires that posts be tagged for drupal and that the feed should only show drupal items. I’m not sure if we side step with our content

Shouldn't take but a few minutes, after completing PR #33 to add a `drupal` tag to our content.

**Comment by sugaroverflow** [comment]
Is this issue complete @cleverington ?

**Comment by cleverington** [comment]
Tags are apparently not as 'quick-an-easy' at they appear.... GitHub Pages does not actually support `jekyll-tagging`, which is kind-of "the thing" for creating and parsing tags for use in an RSS feed.

I found an instruction only we could potentially walk through to add/use our own: http://longqian.me/2017/02/09/github-jekyll-tag/ 

Does the group want to move forward with trying to get on Drupal Planet?  Our last blog post was in May.

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
