### ISSUE TITLE
Put all of the "this is what a drupalist looks like" photos from dcbalt on the site

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#21]
Many of them are on instagram, and that might be the easiest way? but if we use instagram for other things (which we probably should) they will get pushed down. 

It would be great if we could just dump all ~250ish pics onto a page

**Comment by cleverington** [comment]
Does someone have a zip file of these photos? I can get a PR added to get them into the `assets/` folder.  I'm thinking in a  subdirectory named `dcon-balt-booth/` just so there's no confusion into the future.

**Comment by drnikko** [comment]
I can just commit them all to the repo. They're stored locally on my
machine.

There was one person who didnt want to be shared, so I'll leave them out.

**Comment by drnikko** [comment]
Here's a branch!  I forgot to put the issue number in my commit: https://github.com/drupaldiversity/drupaldiversity.github.io/tree/dcbalt-photos

**Comment by sugaroverflow** [comment]
We can maybe put them in a slider or something :D

**Comment by cleverington** [comment]
Assets sync'd. Closing issue. Will review Jekyll tools to see what can be done for a slider...
