### ISSUE TITLE
Blog post about the smiley face pins / flags of approchability. 

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#23]
We could use a short post (no stress - a few paragraphs) about how these worked and maybe things to improve for next camp/con.

https://github.com/drupaldiversity/administration/issues/32

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
