### ISSUE TITLE
Discovery: Explore new options for the DD&I Website

### ISSUE THREAD

**Issue by seanr** [drupaldiversity/drupaldiversity.github.io#35]
### Motivation

A number of Participants have championed the idea that we are a _Drupal_ Community and should therefore be sporting a _Drupal_ site for the DD&I Team.

The overall group almost 100% voted down the idea of trying to host/build on drupal.org because we are not affiliated with the Drupal Association and do not want to misrepresent ourselves.

That said, if memory serves, we once received an offer for hosting from Pantheon via @joshkoenig (forgive me if this is incorrect, it has been a while), so _where_ to put a new site is a non-issue.
However, we *would* need to also pay for Domain Registration if we moved into that direction, so, after Discovery and Planning, we’ll need to run our ideas and plans by the Leadership Team to see if a new site can be in the cards.

### Next steps

 - Analyze existing content
 - Determine requirements for content going forward
 - Determine additional functional requirements (webforms, integrations, etc.)
 - Begin investigating hosting options

**Comment by seanr** [comment]
@cleverington, I'm not surprised Josh would have made that offer and I'm sure it still stands. I've known him for many years and I think he's definitely on board with our overall objectives.

**Comment by sugaroverflow** [comment]
My one concern about building a drupal site would maintenance. Since you are the tech team lead, do you feel that you have enough contributors so that the majority of the work doesn't fall on you? @cleverington 

From a content perspective, I'd be more than happy to put down the requirements in terms of publishing, content types, and users.

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
