### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#5]
We need to figure out what to do with the resources section.  Should we have it at all? Should we link to a wiki on github? Should we do a third thing here?

**Comment by rubyji** [comment]
It would make a good blog post (or series) if we had a blog. But's pretty evergreen.

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
