### ISSUE TITLE
General content strategy

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#6]
I think it would be helpful to have one so that we can then base our choices off of whether or not it fits into a strategy.  I  need someone with content experience to tell us what to do. :)

**Comment by bradleyfields** [comment]
Took a shot at articulating a [content/core strategy statement](https://docs.google.com/presentation/d/1lDfqWiGlcU_HjRzSBWhXC4_uzwxuxJq0liQb1z6kTDc/edit?usp=sharing). Whatever we decide on should ground and guide everything we create, no matter what medium/platform. Though, we could definitely do sub-statements (like a Twitter-specific version).

This draft should be open for anyone with the link to comment, but let me know if not. And it intentionally forks [something I worked on for the DA](https://docs.google.com/presentation/d/1UvGALu0hP050VJ7WSwCdfKYzeguV1od9hU9QkgiEC8M/edit#slide=id.ga3185467d_0_0).

Very open to feedback. Once we're happy enough to get started working with it, next steps could be creating a message framework for our audience, and then mapping those message strategies to the right platforms.

**Comment by drnikko** [comment]
Holy s**t, this is amazing! @bradleyfields thank you so much for working on this. 

I'd love to hear what other people think, but I'm unequivocally on board with slides 12-16.  I think breaking it down that way is so instructive and helpful.   It feels like we can tweak some of the copy on the earlier slides, but that is details.  Overall I love it.

**Comment by techgirlgeek** [comment]
I found this to be awesome!! On it's own it's an amazing presentation, and inclusive representation, of the goals that are being sought after by this group, and the community at large. This is very inspirational, and well done Bradley. Kudos to you!

**Comment by sugaroverflow** [comment]
I love the way slides 12-16 are broken down as well!

I had some trouble understanding slide 2 at first even with the shades legend. It could just be me though :)

**Comment by sparklingrobots** [comment]
Wow! Love this. I want to stand up and applaud, @bradleyfields!  Well done.

**Comment by bradleyfields** [comment]
Updated the [statement slides](https://docs.google.com/presentation/d/1lDfqWiGlcU_HjRzSBWhXC4_uzwxuxJq0liQb1z6kTDc/edit#) to focus only on the content task here.

Whatever we articulate as our reason for creating content should be easily traced to why we exist at all. But I also don't want to confuse this work with the work in progress on the [mission](https://github.com/drupaldiversity/administration/issues/2) and [position](https://github.com/drupaldiversity/administration/issues/22) statements.

**Comment by sugaroverflow** [comment]
Somewhat covered in #100 our social media policy and strategy. Will also be covered by our DD&I statement of values which will be put up today. So closing this issue for now.   

I'd also like to move @bradleyfields slides in our slides and resources for talking about DD&I. Thank you for these, they're great!
