### ISSUE TITLE
Metatags

### ISSUE THREAD

**Issue by cleverington** [drupaldiversity/drupaldiversity.github.io#8]
## Issue

It appears that Drupal Diversity does not rate highly in SEO!  Oh no!  

We need to fix that by upping our metags and other SEO tools.

## Resolution

1. Install the Jekyll SEO tag plugin
https://help.github.com/articles/search-engine-optimization-for-github-pages/
2. Update `_config.yml` file with site information:
https://github.com/jekyll/jekyll-seo-tag#usage
- `title`
- `description`
- `url`
- `author`
- `twitter:username`
- `logo`
- `social`
  * `name`
  * `links`

**Comment by justAChris** [comment]
Need to determine if the meta description can be set per page. Currently it looks like the meta description is re-used sitewide "Drupal Diversity & Inclusion is a collection…". 

We may not have the content (description) for each page right now, but we should ensure this can be changed as that description is pretty important in the search results.

**Comment by laughnan** [comment]
Closing this issue. We have migrated to Drupal 8 at https://www.drupaldiversity.com. Any further work/issues are tracked on Drupal.org at: https://www.drupal.org/project/issues/ddi_contrib
